### ISSUE TITLE
RRO 8.0.2 Beta 1 installs the wrong Rprofile.site

### ISSUE THREAD

**Issue by sfweller** [RevolutionAnalytics/RRO#108]
In RRO 8.0.2 we should now be installing the `Rprofile.site` file from the following location:
`/parallelR/trunk/RevoR/resources/shared/profiles/Rprofile.site`

Currently, because we are using the old Rprofile.site some new Revo packages are not being loaded as they should, for example `RevoUtilsMath` is not being loaded when RRO is launched on Windows.

**Comment by revodavid** [comment]
@sfweller I assume this is fixed now -- please close.

**Comment by sfweller** [comment]
This is still not working as it should. In order for the Intel MKL libraries to work properly with RRO,
we need to make sure that the RevoUtilsMath package is loaded on startup, so that users don't need to do that themselves.

We need to add the following line to the Rprofile.site to automatically load it:
options(defaultPackages = c(getOption("defaultPackages"), "RevoUtilsMath"))

Assigning back to you Nick.....

**Comment by andrie** [comment]
Tagging with 8.0.3 since Stephen reports this is still an issue

**Comment by revodavid** [comment]
@sfweller can you confirm fixed in 8.0.3? If so please close.

**Comment by sfweller** [comment]
I am closing this issue. The Rprofile.site for RRO still does not match the one for RRE. but Rich C. says that was a conscious design decision. It appears to be now the way it is supposed to look like.
